CHOICE_QUESTIONS = [
    {
        "id": "c-arith-001",
        "category": "表达式",
        "difficulty": 3,
        "stem": "下面程序片段的输出结果是？",
        "code": "int a = 19, b = 4;\ncout << a / b + a % b * 2;",
        "options": ["7", "10", "11", "19"],
        "answer": 1,
    },
    {
        "id": "c-loop-001",
        "category": "嵌套循环",
        "difficulty": 4,
        "stem": "下面程序片段的输出结果是？",
        "code": "int cnt = 0;\nfor (int i = 1; i <= 5; i++) {\n    for (int j = 1; j <= i; j++) {\n        if ((i + j) % 2 == 0) {\n            cnt++;\n        }\n    }\n}\ncout << cnt;",
        "options": ["6", "8", "9", "15"],
        "answer": 2,
    },
    {
        "id": "c-string-001",
        "category": "字符串",
        "difficulty": 4,
        "stem": "下面程序片段的输出结果是？",
        "code": "string s = \"p10q25\";\nint x = 0;\nfor (int i = 0; i < s.size(); i++) {\n    if (s[i] >= '0' && s[i] <= '9') {\n        x = x * 10 + (s[i] - '0');\n    }\n}\ncout << x;",
        "options": ["35", "1025", "125", "10025"],
        "answer": 1,
    },
    {
        "id": "c-prime-001",
        "category": "筛法质数",
        "difficulty": 4,
        "stem": "用筛法标记 2 到 70 的合数，最后未被标记的数有多少个？",
        "code": "",
        "options": ["18", "19", "20", "21"],
        "answer": 1,
    },
    {
        "id": "c-sort-001",
        "category": "排序",
        "difficulty": 4,
        "stem": "执行下面一趟冒泡排序后，数组 a 的内容是？",
        "code": "int a[6] = {6, 1, 5, 2, 4, 3};\nfor (int j = 0; j < 5; j++) {\n    if (a[j] > a[j + 1]) {\n        int t = a[j];\n        a[j] = a[j + 1];\n        a[j + 1] = t;\n    }\n}",
        "options": ["{1, 5, 2, 4, 3, 6}", "{1, 2, 3, 4, 5, 6}", "{1, 6, 2, 4, 3, 5}", "{6, 5, 4, 3, 2, 1}"],
        "answer": 0,
    },
    {
        "id": "c-array2-001",
        "category": "二维数组",
        "difficulty": 4,
        "stem": "下面程序片段的输出结果是？",
        "code": "int a[3][3] = {\n    {5, 1, 2},\n    {4, 7, 3},\n    {6, 8, 9}\n};\nint s = 0;\nfor (int i = 0; i < 3; i++) {\n    s += a[i][2 - i];\n}\ncout << s;",
        "options": ["12", "15", "18", "21"],
        "answer": 1,
    },
    {
        "id": "c-rec-001",
        "category": "递归递推",
        "difficulty": 4,
        "stem": "下面函数调用 f(6) 的返回值是？",
        "code": "int f(int n) {\n    if (n <= 2) {\n        return 1;\n    }\n    return f(n - 1) + f(n - 2);\n}",
        "options": ["5", "8", "13", "21"],
        "answer": 1,
    },
    {
        "id": "c-binary-001",
        "category": "二分查找",
        "difficulty": 4,
        "stem": "下面二分查找程序的输出结果是？",
        "code": "int a[7] = {2, 4, 6, 8, 10, 12, 14};\nint l = 0, r = 6, x = 10, ans = -1;\nwhile (l <= r) {\n    int mid = (l + r) / 2;\n    if (a[mid] == x) {\n        ans = mid;\n        break;\n    } else if (a[mid] < x) {\n        l = mid + 1;\n    } else {\n        r = mid - 1;\n    }\n}\ncout << ans;",
        "options": ["3", "4", "5", "-1"],
        "answer": 1,
    },
    {
        "id": "c-logic-001",
        "category": "逻辑表达式",
        "difficulty": 3,
        "stem": "下面程序片段的输出结果是？",
        "code": "int x = 18;\ncout << (x % 2 == 0 && x % 5 == 0 || x % 3 == 0);",
        "options": ["0", "1", "2", "3"],
        "answer": 1,
    },
    {
        "id": "c-enum-001",
        "category": "枚举计数",
        "difficulty": 3,
        "stem": "从数字 1、2、3、4、5 中选出两个不同数字组成两位数，其中偶数有多少个？",
        "code": "",
        "options": ["6", "8", "10", "20"],
        "answer": 1,
    },
    {
        "id": "c-array-001",
        "category": "数组",
        "difficulty": 3,
        "stem": "下面程序片段的输出结果是？",
        "code": "int a[5] = {2, 4, 6, 8, 10};\ncout << a[1] + a[3];",
        "options": ["6", "10", "12", "14"],
        "answer": 2,
    },
    {
        "id": "c-array-002",
        "category": "数组",
        "difficulty": 3,
        "stem": "下面程序片段的输出结果是？",
        "code": "int a[6] = {3, 1, 4, 1, 5, 9};\nint mx = a[0];\nfor (int i = 1; i < 6; i++) {\n    if (a[i] > mx) {\n        mx = a[i];\n    }\n}\ncout << mx;",
        "options": ["1", "4", "5", "9"],
        "answer": 3,
    },
    {
        "id": "c-loop-002",
        "category": "循环",
        "difficulty": 3,
        "stem": "下面程序片段的输出结果是？",
        "code": "int sum = 0;\nfor (int i = 1; i <= 5; i++) {\n    sum += i;\n}\ncout << sum;",
        "options": ["5", "10", "15", "20"],
        "answer": 2,
    },
    {
        "id": "c-sort-002",
        "category": "排序",
        "difficulty": 4,
        "stem": "下面选择排序执行完 i == 0 这一轮后，数组 a 为？",
        "code": "int a[5] = {6, 4, 2, 5, 3};\nint k = 0;\nfor (int j = 1; j < 5; j++) {\n    if (a[j] < a[k]) {\n        k = j;\n    }\n}\nint t = a[0];\na[0] = a[k];\na[k] = t;",
        "options": ["{2, 4, 6, 5, 3}", "{3, 4, 2, 5, 6}", "{6, 4, 2, 5, 3}", "{2, 3, 4, 5, 6}"],
        "answer": 0,
    },
    {
        "id": "c-short-001",
        "category": "逻辑表达式",
        "difficulty": 4,
        "stem": "下面程序片段的输出结果是？",
        "code": "int x = 10;\ncout << (x > 5 || x / 0 == 1);",
        "options": ["0", "1", "运行时错误", "编译错误"],
        "answer": 1,
    },
    {
        "id": "c-div-001",
        "category": "整除统计",
        "difficulty": 3,
        "stem": "1 到 90 中能被 2、3、5 中至少一个整除的整数有多少个？",
        "code": "",
        "options": ["60", "66", "68", "72"],
        "answer": 1,
    },
    {
        "id": "c-factor-001",
        "category": "整除统计",
        "difficulty": 3,
        "stem": "下面程序片段的输出结果是？",
        "code": "int x = 24;\nint cnt = 0;\nfor (int i = 1; i * i <= x; i++) {\n    if (x % i == 0) {\n        cnt++;\n        if (i * i != x) {\n            cnt++;\n        }\n    }\n}\ncout << cnt;",
        "options": ["6", "8", "10", "12"],
        "answer": 1,
    },
]


PROGRAMMING_TASKS = [
    {
        "id": "p-row-col",
        "category": "二维数组",
        "difficulty": 4,
        "title": "矩阵十字和",
        "description": "给定一个 n 行 m 列的整数矩阵，以及一个位置 (x, y)。请输出第 x 行与第 y 列所有元素之和，交叉位置只计算一次。行列编号从 1 开始。",
        "input": "第一行输入 n 和 m。接下来 n 行，每行 m 个整数。最后一行输入 x 和 y。",
        "output": "输出一个整数，表示矩阵十字和。",
        "constraints": "1 <= n, m <= 50；矩阵元素为 0 到 1000 的整数。",
        "tests": [
            {"input": "3 3\n1 2 3\n4 5 6\n7 8 9\n2 2\n", "output": "25\n"},
            {"input": "2 4\n1 1 1 1\n2 2 2 2\n1 3\n", "output": "6\n"},
            {"input": "4 2\n3 5\n7 9\n1 4\n6 8\n4 1\n", "output": "25\n"},
            {"input": "1 5\n2 4 6 8 10\n1 4\n", "output": "30\n"},
            {"input": "2 2\n10 20\n30 40\n2 2\n", "output": "90\n"},
        ],
    },
    {
        "id": "p-prime-count",
        "category": "筛法质数",
        "difficulty": 4,
        "title": "区间质数个数",
        "description": "给定两个整数 L 和 R，请统计闭区间 [L, R] 中质数的个数。",
        "input": "输入一行，包含两个整数 L 和 R。",
        "output": "输出一个整数，表示区间内质数的个数。",
        "constraints": "1 <= L <= R <= 100000。",
        "tests": [
            {"input": "1 10\n", "output": "4\n"},
            {"input": "14 20\n", "output": "2\n"},
            {"input": "30 50\n", "output": "5\n"},
            {"input": "90 100\n", "output": "1\n"},
            {"input": "997 1009\n", "output": "3\n"},
        ],
    },
    {
        "id": "p-tasks",
        "category": "贪心",
        "difficulty": 4,
        "title": "最多完成任务数",
        "description": "有 n 个任务，每个任务需要一定时间。小杨总时间为 T，每个任务最多完成一次。为了完成尽量多的任务，请输出最多能完成几个任务。",
        "input": "第一行输入 n 和 T。第二行输入 n 个正整数，表示每个任务需要的时间。",
        "output": "输出一个整数，表示最多能完成的任务数量。",
        "constraints": "1 <= n <= 1000；1 <= T <= 100000；每个任务耗时为 1 到 100000。",
        "tests": [
            {"input": "5 10\n1 3 4 6 8\n", "output": "3\n"},
            {"input": "6 12\n5 1 2 7 3 4\n", "output": "4\n"},
            {"input": "5 7\n8 9 10 11 12\n", "output": "0\n"},
            {"input": "7 15\n1 1 2 2 3 8 9\n", "output": "5\n"},
            {"input": "8 9\n4 4 4 1 1 1 10 2\n", "output": "5\n"},
        ],
    },
    {
        "id": "p-longest-rise",
        "category": "数组",
        "difficulty": 4,
        "title": "最长连续上升段",
        "description": "给定一个长度为 n 的整数序列，请求出最长连续上升段的长度。连续上升段要求相邻后一个数严格大于前一个数。",
        "input": "第一行输入 n。第二行输入 n 个整数。",
        "output": "输出一个整数，表示最长连续上升段的长度。",
        "constraints": "1 <= n <= 100000；序列元素为 int 范围内整数。",
        "tests": [
            {"input": "5\n1 2 3 2 5\n", "output": "3\n"},
            {"input": "6\n6 5 4 3 2 1\n", "output": "1\n"},
            {"input": "7\n1 3 5 7 9 11 13\n", "output": "7\n"},
            {"input": "8\n2 2 3 4 1 2 3 0\n", "output": "3\n"},
            {"input": "10\n1 2 1 2 3 4 0 1 2 3\n", "output": "4\n"},
        ],
    },
    {
        "id": "p-recurrence",
        "category": "递推",
        "difficulty": 4,
        "title": "递推数列",
        "description": "定义数列 f(1)=1，f(2)=2。当 n>=3 时，f(n)=f(n-1)+2*f(n-2)。给定 n，请输出 f(n)。",
        "input": "输入一个整数 n。",
        "output": "输出 f(n) 的值。",
        "constraints": "1 <= n <= 40，答案在 long long 范围内。",
        "tests": [
            {"input": "1\n", "output": "1\n"},
            {"input": "2\n", "output": "2\n"},
            {"input": "5\n", "output": "16\n"},
            {"input": "10\n", "output": "512\n"},
            {"input": "30\n", "output": "536870912\n"},
        ],
    },
]


OFFICIAL_SOURCE_REFERENCES = [
    {
        "name": "CCF GESP 真题及解析列表",
        "url": "https://gesp.ccf.org.cn/101/1010/index.html",
    },
    {
        "name": "2026 年 3 月 GESP C++ 四级真题 PDF",
        "url": "https://gesp.ccf.org.cn/101/attach/1734124643549216.pdf",
    },
    {
        "name": "2026 年 3 月 GESP C++ 五级真题 PDF",
        "url": "https://gesp.ccf.org.cn/101/attach/1734457367199776.pdf",
    },
]


OFFICIAL_STYLE_CHOICE_QUESTIONS = [
    {
        "id": "c-official-ref-001",
        "category": "引用与指针",
        "difficulty": 4,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "下面程序片段的输出结果是？",
        "code": "int a = 3, b = 5;\nint &r = a;\nr += b;\nb = r - b;\ncout << a << \" \" << b;",
        "options": ["3 5", "8 3", "8 5", "5 3"],
        "answer": 1,
    },
    {
        "id": "c-official-ptr-001",
        "category": "引用与指针",
        "difficulty": 4,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "下面程序片段的输出结果是？",
        "code": "int a[4] = {2, 4, 6, 8};\nint *p = a + 1;\ncout << *(p + 2) - *p;",
        "options": ["2", "4", "6", "8"],
        "answer": 1,
    },
    {
        "id": "c-official-struct-001",
        "category": "结构体排序",
        "difficulty": 4,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "按分数从高到低排序，分数相同按编号从小到大排序。排序后第一个编号是？",
        "code": "struct Node { int id, score; };\nNode a[4] = {{3, 90}, {1, 95}, {2, 95}, {4, 88}};",
        "options": ["1", "2", "3", "4"],
        "answer": 0,
    },
    {
        "id": "c-official-stable-001",
        "category": "排序",
        "difficulty": 4,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "如果只按分数从高到低使用 stable_sort，分数相同的元素会怎样？",
        "code": "",
        "options": ["一定按编号从小到大", "保持原来的相对顺序", "随机排列", "一定按编号从大到小"],
        "answer": 1,
    },
    {
        "id": "c-official-rec-001",
        "category": "递归递推",
        "difficulty": 4,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "下面函数调用 f(5) 的返回值是？",
        "code": "int f(int n) {\n    if (n <= 1) return n;\n    return f(n - 1) + f(n - 2) + 1;\n}",
        "options": ["8", "10", "12", "15"],
        "answer": 2,
    },
    {
        "id": "c-official-insert-001",
        "category": "排序",
        "difficulty": 4,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "下面插入排序执行到 i == 2 这一轮结束后，数组 a 为？",
        "code": "int a[4] = {5, 2, 4, 1};\nfor (int i = 1; i <= 2; i++) {\n    int x = a[i], j = i - 1;\n    while (j >= 0 && a[j] > x) {\n        a[j + 1] = a[j];\n        j--;\n    }\n    a[j + 1] = x;\n}",
        "options": ["{2, 4, 5, 1}", "{2, 5, 4, 1}", "{1, 2, 4, 5}", "{4, 2, 5, 1}"],
        "answer": 0,
    },
    {
        "id": "c-official-gcd-001",
        "category": "数论",
        "difficulty": 4,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "下面程序片段的输出结果是？",
        "code": "int a = 48, b = 18;\nwhile (b != 0) {\n    int t = a % b;\n    a = b;\n    b = t;\n}\ncout << a;",
        "options": ["3", "6", "12", "18"],
        "answer": 1,
    },
    {
        "id": "c-official-sieve-001",
        "category": "筛法质数",
        "difficulty": 4,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "1 到 100 中质数的个数是？",
        "code": "",
        "options": ["23", "24", "25", "26"],
        "answer": 2,
    },
    {
        "id": "c-official-lower-001",
        "category": "二分查找",
        "difficulty": 4,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "下面程序片段输出的是数组中第一个大于等于 7 的位置下标，结果是？",
        "code": "int a[5] = {1, 3, 7, 7, 9};\nint l = 0, r = 5;\nwhile (l < r) {\n    int mid = (l + r) / 2;\n    if (a[mid] >= 7) r = mid;\n    else l = mid + 1;\n}\ncout << l;",
        "options": ["1", "2", "3", "4"],
        "answer": 1,
    },
    {
        "id": "c-official-complexity-001",
        "category": "复杂度",
        "difficulty": 5,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "下面程序片段的时间复杂度最接近哪一项？",
        "code": "for (int i = 1; i <= n; i *= 2) {\n    for (int j = 1; j <= n; j++) {\n        ans++;\n    }\n}",
        "options": ["O(n)", "O(n log n)", "O(n^2)", "O(log n)"],
        "answer": 1,
    },
    {
        "id": "c-official-exception-001",
        "category": "异常处理",
        "difficulty": 4,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "下面程序片段的输出结果是？",
        "code": "try {\n    throw 3;\n    cout << 1;\n} catch (int x) {\n    cout << x + 2;\n}",
        "options": ["1", "3", "5", "没有输出"],
        "answer": 2,
    },
    {
        "id": "c-official-vector-001",
        "category": "STL 基础",
        "difficulty": 4,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "下面程序片段的输出结果是？",
        "code": "vector<int> v;\nv.push_back(2);\nv.push_back(5);\nv.push_back(7);\nv.pop_back();\ncout << v.size() << \" \" << v.back();",
        "options": ["2 5", "2 7", "3 5", "3 7"],
        "answer": 0,
    },
    {
        "id": "c-official-string-002",
        "category": "字符串",
        "difficulty": 4,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "下面程序片段的输出结果是？",
        "code": "string s = \"abacaba\";\nint pos = s.find(\"ca\");\ns.erase(pos, 2);\ncout << s;",
        "options": ["ababa", "abacaba", "abaca", "abacba"],
        "answer": 0,
    },
    {
        "id": "c-official-list-001",
        "category": "链表基础",
        "difficulty": 5,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "单链表中常使用虚拟头结点，主要好处是？",
        "code": "",
        "options": ["减少内存到 0", "统一处理删除头结点和普通结点", "让链表自动排序", "让查找复杂度变成 O(1)"],
        "answer": 1,
    },
    {
        "id": "c-official-stack-001",
        "category": "栈",
        "difficulty": 4,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "判断括号序列是否匹配，最常用的数据结构是？",
        "code": "",
        "options": ["队列", "栈", "堆", "并查集"],
        "answer": 1,
    },
    {
        "id": "c-official-queue-001",
        "category": "队列",
        "difficulty": 4,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "下面队列操作后，队首元素是？",
        "code": "queue<int> q;\nq.push(3);\nq.push(5);\nq.pop();\nq.push(7);\ncout << q.front();",
        "options": ["3", "5", "7", "没有元素"],
        "answer": 1,
    },
    {
        "id": "c-official-prefix-001",
        "category": "前缀和",
        "difficulty": 4,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "已知 a={2,4,1,7,3}，若 s[i] 表示前 i 个数之和，则区间 [2,4] 的和是？",
        "code": "",
        "options": ["10", "11", "12", "14"],
        "answer": 2,
    },
    {
        "id": "c-official-two-pointer-001",
        "category": "双指针",
        "difficulty": 5,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "有序数组中统计和为 x 的两数对，常用的线性做法是？",
        "code": "",
        "options": ["双指针从两端向中间移动", "每次随机选两个数", "只检查相邻元素", "先把数组倒序再线性扫描"],
        "answer": 0,
    },
    {
        "id": "c-official-dp-001",
        "category": "动态规划入门",
        "difficulty": 5,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "若 dp[i] 表示走到第 i 级台阶的方法数，每次可走 1 或 2 级，则递推式是？",
        "code": "",
        "options": ["dp[i]=dp[i-1]+dp[i-2]", "dp[i]=dp[i-1]*2", "dp[i]=i*i", "dp[i]=dp[i-2]-dp[i-1]"],
        "answer": 0,
    },
    {
        "id": "c-official-rec-stack-001",
        "category": "递归递推",
        "difficulty": 5,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "递归函数如果没有正确的终止条件，最可能出现的问题是？",
        "code": "",
        "options": ["自动排序", "栈空间耗尽", "编译器自动优化为循环", "变量自动清零"],
        "answer": 1,
    },
    {
        "id": "c-official-sort-complexity-001",
        "category": "复杂度",
        "difficulty": 4,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "对 n 个整数使用 sort 函数排序，平均时间复杂度通常认为是？",
        "code": "",
        "options": ["O(n)", "O(log n)", "O(n log n)", "O(n^2)"],
        "answer": 2,
    },
    {
        "id": "c-official-mod-001",
        "category": "数论",
        "difficulty": 4,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "下面程序片段的输出结果是？",
        "code": "int ans = 1;\nfor (int i = 1; i <= 5; i++) {\n    ans = ans * 2 % 7;\n}\ncout << ans;",
        "options": ["1", "2", "4", "5"],
        "answer": 2,
    },
    {
        "id": "c-official-map-001",
        "category": "STL 基础",
        "difficulty": 5,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "下面程序片段的输出结果是？",
        "code": "map<string, int> mp;\nmp[\"a\"]++;\nmp[\"b\"] += 2;\nmp[\"a\"] += 3;\ncout << mp[\"a\"] << \" \" << mp.size();",
        "options": ["3 2", "4 2", "4 3", "1 2"],
        "answer": 1,
    },
    {
        "id": "c-official-set-001",
        "category": "STL 基础",
        "difficulty": 5,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "下面程序片段的输出结果是？",
        "code": "set<int> s;\ns.insert(3);\ns.insert(1);\ns.insert(3);\ncout << s.size() << \" \" << *s.begin();",
        "options": ["2 1", "3 1", "2 3", "3 3"],
        "answer": 0,
    },
    {
        "id": "c-official-matrix-001",
        "category": "二维数组",
        "difficulty": 4,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "下面程序片段的输出结果是？",
        "code": "int a[2][3] = {{1, 2, 3}, {4, 5, 6}};\nint s = 0;\nfor (int i = 0; i < 2; i++) {\n    for (int j = 0; j < 3; j++) {\n        if ((i + j) % 2 == 0) s += a[i][j];\n    }\n}\ncout << s;",
        "options": ["7", "9", "10", "12"],
        "answer": 1,
    },
    {
        "id": "c-official-bigint-001",
        "category": "高精度入门",
        "difficulty": 5,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "计算很大的非负整数加法时，通常应该怎样处理？",
        "code": "",
        "options": ["直接用 int", "把数字作为字符串逐位处理进位", "只保留最后一位", "一定转换成 double"],
        "answer": 1,
    },
    {
        "id": "c-official-bfs-001",
        "category": "搜索入门",
        "difficulty": 5,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "在无权图中求最短步数，常用的搜索方法是？",
        "code": "",
        "options": ["深度优先搜索", "广度优先搜索", "选择排序", "二分答案"],
        "answer": 1,
    },
    {
        "id": "c-official-greedy-001",
        "category": "贪心",
        "difficulty": 4,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "为了在总时间 T 内完成尽量多的任务，每个任务耗时已知且价值相同，合理的贪心策略是？",
        "code": "",
        "options": ["优先选择耗时短的任务", "优先选择耗时长的任务", "按输入顺序固定选择", "随机选择"],
        "answer": 0,
    },
    {
        "id": "c-official-enum-002",
        "category": "枚举计数",
        "difficulty": 4,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "从 1 到 9 中选择两个不同数字组成两位数，且十位小于个位，这样的数有多少个？",
        "code": "",
        "options": ["18", "24", "36", "72"],
        "answer": 2,
    },
    {
        "id": "c-official-bit-001",
        "category": "位运算入门",
        "difficulty": 5,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "下面程序片段的输出结果是？",
        "code": "int x = 6;\ncout << (x & 1);",
        "options": ["0", "1", "2", "6"],
        "answer": 0,
    },
    {
        "id": "c-official-loop-003",
        "category": "循环",
        "difficulty": 4,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "下面程序片段的输出结果是？",
        "code": "int s = 0;\nfor (int i = 1; i <= 20; i++) {\n    if (i % 3 == 0) continue;\n    if (i % 5 == 0) s += i;\n}\ncout << s;",
        "options": ["30", "35", "50", "60"],
        "answer": 1,
    },
    {
        "id": "c-official-binary-answer-001",
        "category": "二分答案",
        "difficulty": 5,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "二分答案通常适用于哪类问题？",
        "code": "",
        "options": ["答案具有单调可判定性", "答案必须是字符串", "只能处理递归问题", "只能处理二维数组"],
        "answer": 0,
    },
    {
        "id": "c-official-file-001",
        "category": "文件与流",
        "difficulty": 4,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "在 C++ 中，向文本文件写入数据通常可以使用哪个类？",
        "code": "",
        "options": ["ifstream", "ofstream", "stringstream", "iostream"],
        "answer": 1,
    },
    {
        "id": "c-official-priority-001",
        "category": "STL 基础",
        "difficulty": 5,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "priority_queue<int> 默认情况下，top() 返回什么？",
        "code": "",
        "options": ["最小元素", "最大元素", "最早插入的元素", "最后插入的元素"],
        "answer": 1,
    },
    {
        "id": "c-official-search-002",
        "category": "搜索入门",
        "difficulty": 5,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "深度优先搜索回溯时，常见的操作是？",
        "code": "",
        "options": ["撤销当前选择，尝试下一个选择", "永久删除所有数据", "只执行一次循环", "直接输出排序结果"],
        "answer": 0,
    },
    {
        "id": "c-official-array-003",
        "category": "数组",
        "difficulty": 4,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "stem": "下面程序片段的输出结果是？",
        "code": "int a[5] = {1, 3, 5, 7, 9};\nfor (int i = 0; i < 2; i++) swap(a[i], a[4 - i]);\ncout << a[1] << \" \" << a[3];",
        "options": ["3 7", "7 3", "5 5", "9 1"],
        "answer": 1,
    },
]


OFFICIAL_STYLE_PROGRAMMING_TASKS = [
    {
        "id": "p-official-gcd-lcm",
        "category": "数论",
        "difficulty": 4,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "title": "最大公约数与最小公倍数",
        "description": "给定两个正整数 a 和 b，请输出它们的最大公约数和最小公倍数。",
        "input": "输入一行，包含两个正整数 a 和 b。",
        "output": "输出两个整数，分别表示最大公约数和最小公倍数。",
        "constraints": "1 <= a, b <= 100000。",
        "tests": [
            {"input": "12 18\n", "output": "6 36\n"},
            {"input": "7 13\n", "output": "1 91\n"},
            {"input": "100 25\n", "output": "25 100\n"},
            {"input": "48 180\n", "output": "12 720\n"},
            {"input": "99991 1\n", "output": "1 99991\n"},
        ],
    },
    {
        "id": "p-official-prefix-sum",
        "category": "前缀和",
        "difficulty": 4,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "title": "区间和查询",
        "description": "给定长度为 n 的整数序列和 q 次询问。每次询问给出 l 和 r，请输出区间 [l, r] 的元素和。",
        "input": "第一行输入 n 和 q。第二行输入 n 个整数。接下来 q 行，每行输入 l 和 r。",
        "output": "对每次询问输出一行答案。",
        "constraints": "1 <= n, q <= 100000；元素绝对值不超过 1000；下标从 1 开始。",
        "tests": [
            {"input": "5 3\n2 4 1 7 3\n1 3\n2 4\n4 5\n", "output": "7\n12\n10\n"},
            {"input": "3 2\n10 -2 5\n1 1\n1 3\n", "output": "10\n13\n"},
            {"input": "6 2\n1 1 1 1 1 1\n2 5\n3 3\n", "output": "4\n1\n"},
            {"input": "4 1\n5 6 7 8\n1 4\n", "output": "26\n"},
            {"input": "5 2\n3 -1 4 -1 5\n2 4\n3 5\n", "output": "2\n8\n"},
        ],
    },
    {
        "id": "p-official-sort-students",
        "category": "结构体排序",
        "difficulty": 4,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "title": "成绩排序",
        "description": "给定 n 名学生的编号和成绩，请按成绩从高到低排序；成绩相同则编号小的排在前面。输出排序后的编号。",
        "input": "第一行输入 n。接下来 n 行，每行输入一个编号 id 和一个成绩 score。",
        "output": "输出一行 n 个整数，表示排序后的编号。",
        "constraints": "1 <= n <= 1000；1 <= id <= 100000；0 <= score <= 100。",
        "tests": [
            {"input": "4\n3 90\n1 95\n2 95\n4 88\n", "output": "1 2 3 4\n"},
            {"input": "3\n10 60\n5 60\n7 80\n", "output": "7 5 10\n"},
            {"input": "5\n1 100\n2 99\n3 99\n4 80\n5 100\n", "output": "1 5 2 3 4\n"},
            {"input": "1\n42 77\n", "output": "42\n"},
            {"input": "4\n8 70\n6 70\n7 70\n5 71\n", "output": "5 6 7 8\n"},
        ],
    },
    {
        "id": "p-official-prime-pair",
        "category": "筛法质数",
        "difficulty": 5,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "title": "相邻质数对",
        "description": "给定正整数 n，请统计不超过 n 的质数对 (p, p+2) 有多少个，其中 p 和 p+2 都是质数。",
        "input": "输入一个整数 n。",
        "output": "输出一个整数，表示质数对数量。",
        "constraints": "1 <= n <= 1000000。",
        "tests": [
            {"input": "10\n", "output": "2\n"},
            {"input": "20\n", "output": "4\n"},
            {"input": "50\n", "output": "6\n"},
            {"input": "100\n", "output": "8\n"},
            {"input": "5\n", "output": "1\n"},
        ],
    },
    {
        "id": "p-official-delete-value",
        "category": "链表基础",
        "difficulty": 5,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "title": "删除指定数",
        "description": "给定一个长度为 n 的整数序列和一个整数 x，请删除序列中所有等于 x 的元素，并按原顺序输出剩余元素。如果没有剩余元素，输出 EMPTY。",
        "input": "第一行输入 n 和 x。第二行输入 n 个整数。",
        "output": "输出删除后的序列，元素之间用一个空格分隔；若为空则输出 EMPTY。",
        "constraints": "1 <= n <= 100000；整数在 int 范围内。",
        "tests": [
            {"input": "5 3\n1 3 2 3 4\n", "output": "1 2 4\n"},
            {"input": "4 7\n7 7 7 7\n", "output": "EMPTY\n"},
            {"input": "3 1\n2 3 4\n", "output": "2 3 4\n"},
            {"input": "6 2\n2 1 2 2 3 2\n", "output": "1 3\n"},
            {"input": "1 5\n5\n", "output": "EMPTY\n"},
        ],
    },
    {
        "id": "p-official-brackets",
        "category": "栈",
        "difficulty": 5,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "title": "括号匹配",
        "description": "给定一个只包含小括号和中括号的字符串，请判断括号是否完全匹配。",
        "input": "输入一行字符串 s。",
        "output": "如果匹配输出 YES，否则输出 NO。",
        "constraints": "1 <= |s| <= 100000。",
        "tests": [
            {"input": "([]())\n", "output": "YES\n"},
            {"input": "([)]\n", "output": "NO\n"},
            {"input": "(([]))\n", "output": "YES\n"},
            {"input": "([[]])()\n", "output": "YES\n"},
            {"input": "(()\n", "output": "NO\n"},
        ],
    },
    {
        "id": "p-official-two-sum-pairs",
        "category": "双指针",
        "difficulty": 5,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "title": "两数之和对数",
        "description": "给定一个非降序整数序列和目标值 x，请统计满足 a[i] + a[j] = x 且 i < j 的数对数量。",
        "input": "第一行输入 n 和 x。第二行输入 n 个非降序整数。",
        "output": "输出一个整数，表示数对数量。",
        "constraints": "1 <= n <= 100000；元素和 x 在 int 范围内。",
        "tests": [
            {"input": "5 6\n1 2 3 4 5\n", "output": "2\n"},
            {"input": "4 4\n2 2 2 2\n", "output": "6\n"},
            {"input": "6 7\n1 1 2 5 6 6\n", "output": "5\n"},
            {"input": "3 10\n1 2 3\n", "output": "0\n"},
            {"input": "7 8\n1 2 2 3 5 6 7\n", "output": "4\n"},
        ],
    },
    {
        "id": "p-official-stairs",
        "category": "动态规划入门",
        "difficulty": 5,
        "source": "CCF GESP C++ 四级/五级公开真题考点改编",
        "title": "上台阶",
        "description": "有 n 级台阶，每次可以上 1 级或 2 级。请输出走到第 n 级台阶的方法数。",
        "input": "输入一个整数 n。",
        "output": "输出一个整数，表示方法数。",
        "constraints": "1 <= n <= 45，答案在 long long 范围内。",
        "tests": [
            {"input": "1\n", "output": "1\n"},
            {"input": "2\n", "output": "2\n"},
            {"input": "5\n", "output": "8\n"},
            {"input": "10\n", "output": "89\n"},
            {"input": "20\n", "output": "10946\n"},
        ],
    },
]


CHOICE_QUESTIONS.extend(OFFICIAL_STYLE_CHOICE_QUESTIONS)
PROGRAMMING_TASKS.extend(OFFICIAL_STYLE_PROGRAMMING_TASKS)


OFFICIAL_STYLE_CHOICE_QUESTIONS_EXTRA = [
    {
        "id": "c-official-extra-func-001",
        "category": "函数",
        "difficulty": 4,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "下面程序片段的输出结果是？",
        "code": "int f(int x) {\n    x += 3;\n    return x * 2;\n}\nint a = 4;\ncout << f(a) << \" \" << a;",
        "options": ["14 4", "14 7", "8 4", "8 7"],
        "answer": 0,
    },
    {
        "id": "c-official-extra-scope-001",
        "category": "变量作用域",
        "difficulty": 4,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "下面程序片段的输出结果是？",
        "code": "int x = 5;\n{\n    int x = 8;\n    x += 2;\n}\ncout << x;",
        "options": ["5", "7", "8", "10"],
        "answer": 0,
    },
    {
        "id": "c-official-extra-char-001",
        "category": "字符处理",
        "difficulty": 4,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "下面程序片段的输出结果是？",
        "code": "char c = 'D';\ncout << char(c - 2);",
        "options": ["A", "B", "C", "F"],
        "answer": 1,
    },
    {
        "id": "c-official-extra-ascii-001",
        "category": "字符处理",
        "difficulty": 4,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "下面程序片段的输出结果是？",
        "code": "string s = \"A1b2\";\nint cnt = 0;\nfor (char c : s) {\n    if (c >= 'A' && c <= 'Z') cnt++;\n}\ncout << cnt;",
        "options": ["0", "1", "2", "4"],
        "answer": 1,
    },
    {
        "id": "c-official-extra-ref-002",
        "category": "引用与指针",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "下面程序片段的输出结果是？",
        "code": "void change(int &x, int y) {\n    x += y;\n    y += x;\n}\nint a = 2, b = 3;\nchange(a, b);\ncout << a << \" \" << b;",
        "options": ["2 3", "5 3", "5 8", "2 8"],
        "answer": 1,
    },
    {
        "id": "c-official-extra-pointer-002",
        "category": "引用与指针",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "下面程序片段的输出结果是？",
        "code": "int x = 4;\nint *p = &x;\n*p = *p + 6;\ncout << x;",
        "options": ["4", "6", "10", "地址值"],
        "answer": 2,
    },
    {
        "id": "c-official-extra-string-count-001",
        "category": "字符串",
        "difficulty": 4,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "下面程序片段的输出结果是？",
        "code": "string s = \"contest2026\";\nint cnt = 0;\nfor (char c : s) {\n    if (c >= '0' && c <= '9') cnt++;\n}\ncout << cnt;",
        "options": ["2", "3", "4", "7"],
        "answer": 2,
    },
    {
        "id": "c-official-extra-string-substr-001",
        "category": "字符串",
        "difficulty": 4,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "下面程序片段的输出结果是？",
        "code": "string s = \"abcdef\";\ncout << s.substr(2, 3);",
        "options": ["abc", "bcd", "cde", "def"],
        "answer": 2,
    },
    {
        "id": "c-official-extra-vector-002",
        "category": "STL 基础",
        "difficulty": 4,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "下面程序片段的输出结果是？",
        "code": "vector<int> v = {3, 1, 4};\nv.insert(v.begin() + 1, 2);\ncout << v[1] << \" \" << v.size();",
        "options": ["1 3", "2 4", "3 4", "4 3"],
        "answer": 1,
    },
    {
        "id": "c-official-extra-sort-003",
        "category": "排序",
        "difficulty": 4,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "下面程序片段的输出结果是？",
        "code": "vector<int> a = {4, 1, 3, 2};\nsort(a.begin(), a.end(), greater<int>());\ncout << a[0] << a[3];",
        "options": ["14", "41", "12", "43"],
        "answer": 1,
    },
    {
        "id": "c-official-extra-struct-002",
        "category": "结构体排序",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "若比较规则为先按 x 升序，x 相同按 y 降序，则下面三个点排序后第二个点是？",
        "code": "(2, 3), (1, 5), (2, 7)",
        "options": ["(1, 5)", "(2, 3)", "(2, 7)", "无法确定"],
        "answer": 2,
    },
    {
        "id": "c-official-extra-binary-002",
        "category": "二分查找",
        "difficulty": 4,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "在有序数组 {2,4,6,8,10} 中查找 7，标准二分查找最终会得到什么结果？",
        "code": "",
        "options": ["下标 2", "下标 3", "未找到", "下标 4"],
        "answer": 2,
    },
    {
        "id": "c-official-extra-binary-answer-002",
        "category": "二分答案",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "二分答案中，若 check(mid) 为真时可以尝试更小答案，通常应该怎样更新区间？",
        "code": "",
        "options": ["r = mid", "l = mid + 1", "l = 0", "直接退出"],
        "answer": 0,
    },
    {
        "id": "c-official-extra-prefix-002",
        "category": "前缀和",
        "difficulty": 4,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "一维前缀和 s[i] 表示前 i 个元素之和，区间 [l,r] 的和应写作？",
        "code": "",
        "options": ["s[r]-s[l]", "s[r]-s[l-1]", "s[l]+s[r]", "s[r+1]-s[l+1]"],
        "answer": 1,
    },
    {
        "id": "c-official-extra-prefix2d-001",
        "category": "二维前缀和",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "二维前缀和查询矩形 (x1,y1) 到 (x2,y2) 时，需要加回哪一块被减了两次的区域？",
        "code": "",
        "options": ["s[x1-1][y1-1]", "s[x2][y2]", "s[x1][y2]", "s[x2][y1]"],
        "answer": 0,
    },
    {
        "id": "c-official-extra-dp-002",
        "category": "动态规划入门",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "0/1 背包中每件物品最多选一次，一维 dp 通常应如何枚举容量？",
        "code": "",
        "options": ["从小到大", "从大到小", "随机", "只枚举一次容量 0"],
        "answer": 1,
    },
    {
        "id": "c-official-extra-dp-003",
        "category": "动态规划入门",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "最长不下降子序列问题中，状态 dp[i] 通常表示什么？",
        "code": "",
        "options": ["以第 i 个数结尾的最优长度", "前 i 个数的总和", "第 i 个数的下标", "排序后的第 i 个数"],
        "answer": 0,
    },
    {
        "id": "c-official-extra-stack-002",
        "category": "栈",
        "difficulty": 4,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "下面栈操作后，栈顶元素是？",
        "code": "stack<int> st;\nst.push(1);\nst.push(2);\nst.pop();\nst.push(3);\ncout << st.top();",
        "options": ["1", "2", "3", "栈为空"],
        "answer": 2,
    },
    {
        "id": "c-official-extra-queue-002",
        "category": "队列",
        "difficulty": 4,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "普通队列 queue 的出队顺序符合哪一原则？",
        "code": "",
        "options": ["后进先出", "先进先出", "随机出队", "按大小出队"],
        "answer": 1,
    },
    {
        "id": "c-official-extra-deque-001",
        "category": "STL 基础",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "deque 与 queue 相比，deque 的一个典型特点是？",
        "code": "",
        "options": ["只能从队尾删除", "可以在两端插入和删除", "不能存整数", "会自动去重"],
        "answer": 1,
    },
    {
        "id": "c-official-extra-map-002",
        "category": "STL 基础",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "map 中的键 key 具有哪个特点？",
        "code": "",
        "options": ["可以重复", "必须唯一", "只能是 int", "不会排序"],
        "answer": 1,
    },
    {
        "id": "c-official-extra-set-002",
        "category": "STL 基础",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "set<int> s 插入 5、2、5 后，s.size() 的值是？",
        "code": "",
        "options": ["1", "2", "3", "5"],
        "answer": 1,
    },
    {
        "id": "c-official-extra-greedy-002",
        "category": "贪心",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "活动选择问题中，想安排最多互不重叠活动，经典贪心策略是？",
        "code": "",
        "options": ["优先结束早的活动", "优先开始晚的活动", "优先持续时间长的活动", "随机选择"],
        "answer": 0,
    },
    {
        "id": "c-official-extra-interval-001",
        "category": "区间问题",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "合并区间时，通常先按什么排序？",
        "code": "",
        "options": ["左端点升序", "右端点降序", "区间长度降序", "无需排序"],
        "answer": 0,
    },
    {
        "id": "c-official-extra-bfs-002",
        "category": "搜索入门",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "BFS 通常使用哪种数据结构维护待扩展状态？",
        "code": "",
        "options": ["栈", "队列", "集合", "递归函数栈"],
        "answer": 1,
    },
    {
        "id": "c-official-extra-dfs-001",
        "category": "搜索入门",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "DFS 搜索所有排列时，为避免重复选择同一元素，常使用什么数组？",
        "code": "",
        "options": ["used 标记数组", "答案前缀和数组", "排序比较数组", "质数筛数组"],
        "answer": 0,
    },
    {
        "id": "c-official-extra-rec-002",
        "category": "递归递推",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "下面递归函数 g(10) 的返回值是？",
        "code": "int g(int n) {\n    if (n == 0) return 0;\n    return 1 + g(n / 2);\n}",
        "options": ["3", "4", "5", "10"],
        "answer": 1,
    },
    {
        "id": "c-official-extra-graph-001",
        "category": "图论入门",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "用邻接表存储 n 个点 m 条边的无向图，边信息通常会存储几次？",
        "code": "",
        "options": ["m 次", "2m 次", "n 次", "n+m 次"],
        "answer": 1,
    },
    {
        "id": "c-official-extra-topo-001",
        "category": "图论入门",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "拓扑排序适用于哪类图？",
        "code": "",
        "options": ["有向无环图", "任意无向图", "完全图", "只有一个点的图"],
        "answer": 0,
    },
    {
        "id": "c-official-extra-union-001",
        "category": "并查集入门",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "并查集最常用于解决哪类问题？",
        "code": "",
        "options": ["动态维护连通性", "字符串翻转", "数组排序", "浮点数四舍五入"],
        "answer": 0,
    },
    {
        "id": "c-official-extra-heap-001",
        "category": "堆",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "使用 priority_queue<int, vector<int>, greater<int>> pq 时，pq.top() 返回什么？",
        "code": "",
        "options": ["最小元素", "最大元素", "随机元素", "元素个数"],
        "answer": 0,
    },
    {
        "id": "c-official-extra-modpow-001",
        "category": "数论",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "快速幂计算 a^b mod m 时，b 每次除以 2，主要利用了什么思想？",
        "code": "",
        "options": ["二进制拆分指数", "线性枚举所有答案", "冒泡排序", "字符串匹配"],
        "answer": 0,
    },
    {
        "id": "c-official-extra-lcm-001",
        "category": "数论",
        "difficulty": 4,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "已知 gcd(a,b)=6，a=18，b=24，则 lcm(a,b) 是？",
        "code": "",
        "options": ["42", "48", "72", "432"],
        "answer": 2,
    },
    {
        "id": "c-official-extra-bit-002",
        "category": "位运算入门",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "表达式 x & (x - 1) 常用于做什么？",
        "code": "",
        "options": ["去掉 x 的最低位 1", "把 x 变成 0", "判断 x 是否为负数", "求 x 的平方"],
        "answer": 0,
    },
    {
        "id": "c-official-extra-complexity-002",
        "category": "复杂度",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "下面程序片段的时间复杂度是？",
        "code": "for (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= i; j++) {\n        ans++;\n    }\n}",
        "options": ["O(n)", "O(log n)", "O(n log n)", "O(n^2)"],
        "answer": 3,
    },
    {
        "id": "c-official-extra-memory-001",
        "category": "复杂度",
        "difficulty": 4,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "声明 int a[1000][1000] 大约需要多少字节内存？",
        "code": "",
        "options": ["约 4KB", "约 400KB", "约 4MB", "约 40MB"],
        "answer": 2,
    },
    {
        "id": "c-official-extra-file-002",
        "category": "文件与流",
        "difficulty": 4,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "stringstream 常用于什么场景？",
        "code": "",
        "options": ["在字符串和数据之间进行格式化读写", "创建图形界面", "自动连接网络", "替代所有数组"],
        "answer": 0,
    },
    {
        "id": "c-official-extra-random-001",
        "category": "模拟",
        "difficulty": 4,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "模拟题中，最重要的实现原则通常是？",
        "code": "",
        "options": ["严格按照题意维护状态变化", "只写排序函数", "完全忽略边界条件", "一定使用递归"],
        "answer": 0,
    },
    {
        "id": "c-official-extra-date-001",
        "category": "模拟",
        "difficulty": 4,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "判断闰年时，下面哪个条件是正确的？",
        "code": "",
        "options": ["能被 4 整除就是闰年", "能被 400 整除，或能被 4 整除但不能被 100 整除", "能被 100 整除就是闰年", "奇数年都是闰年"],
        "answer": 1,
    },
    {
        "id": "c-official-extra-grid-001",
        "category": "二维数组",
        "difficulty": 4,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "stem": "在 n 行 m 列矩阵中，若使用 0 下标，最后一行最后一列的位置是？",
        "code": "",
        "options": ["(n,m)", "(n-1,m-1)", "(1,1)", "(m-1,n-1)"],
        "answer": 1,
    },
]


OFFICIAL_STYLE_PROGRAMMING_TASKS_EXTRA = [
    {
        "id": "p-official-count-components",
        "category": "并查集入门",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "title": "连通块数量",
        "description": "有 n 个点和 m 条无向边。请输出图中连通块的数量。",
        "input": "第一行输入 n 和 m。接下来 m 行，每行输入一条边的两个端点 u 和 v。",
        "output": "输出一个整数，表示连通块数量。",
        "constraints": "1 <= n <= 100000；0 <= m <= 200000。",
        "tests": [
            {"input": "5 3\n1 2\n2 3\n4 5\n", "output": "2\n"},
            {"input": "4 0\n", "output": "4\n"},
            {"input": "4 3\n1 2\n2 3\n3 4\n", "output": "1\n"},
            {"input": "6 2\n1 2\n4 5\n", "output": "4\n"},
            {"input": "3 3\n1 2\n2 3\n1 3\n", "output": "1\n"},
        ],
    },
    {
        "id": "p-official-merge-intervals",
        "category": "区间问题",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "title": "合并区间",
        "description": "给定 n 个闭区间，请合并所有有交集的区间，输出合并后区间的数量。",
        "input": "第一行输入 n。接下来 n 行，每行输入 l 和 r。",
        "output": "输出一个整数，表示合并后的区间数量。",
        "constraints": "1 <= n <= 100000；0 <= l <= r <= 1000000000。",
        "tests": [
            {"input": "3\n1 3\n2 5\n7 8\n", "output": "2\n"},
            {"input": "4\n1 2\n3 4\n5 6\n7 8\n", "output": "4\n"},
            {"input": "4\n1 10\n2 3\n4 5\n9 12\n", "output": "1\n"},
            {"input": "1\n5 5\n", "output": "1\n"},
            {"input": "5\n1 2\n2 3\n4 6\n6 9\n10 10\n", "output": "3\n"},
        ],
    },
    {
        "id": "p-official-grid-bfs",
        "category": "搜索入门",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "title": "迷宫最短路",
        "description": "给定一个 n 行 m 列迷宫，'.' 表示可走，'#' 表示障碍。从左上角走到右下角，每次可向上下左右移动一格。输出最少步数，无法到达输出 -1。",
        "input": "第一行输入 n 和 m。接下来 n 行输入迷宫。",
        "output": "输出一个整数，表示最少步数。",
        "constraints": "1 <= n, m <= 200。",
        "tests": [
            {"input": "3 3\n...\n.#.\n...\n", "output": "4\n"},
            {"input": "2 2\n.#\n#.\n", "output": "-1\n"},
            {"input": "1 1\n.\n", "output": "0\n"},
            {"input": "3 4\n....\n####\n....\n", "output": "-1\n"},
            {"input": "4 4\n....\n.##.\n...#\n#...\n", "output": "6\n"},
        ],
    },
    {
        "id": "p-official-knapsack01",
        "category": "动态规划入门",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "title": "01 背包",
        "description": "有 n 件物品，每件物品有体积 w 和价值 v，背包容量为 W。每件物品最多选择一次，请输出最大总价值。",
        "input": "第一行输入 n 和 W。接下来 n 行，每行输入 w 和 v。",
        "output": "输出一个整数，表示最大价值。",
        "constraints": "1 <= n <= 200；1 <= W <= 10000。",
        "tests": [
            {"input": "3 5\n2 6\n3 10\n4 12\n", "output": "16\n"},
            {"input": "4 7\n6 10\n3 5\n4 6\n2 4\n", "output": "11\n"},
            {"input": "2 3\n4 10\n5 20\n", "output": "0\n"},
            {"input": "1 5\n5 99\n", "output": "99\n"},
            {"input": "5 10\n2 3\n2 4\n6 9\n5 8\n4 6\n", "output": "16\n"},
        ],
    },
    {
        "id": "p-official-lis",
        "category": "动态规划入门",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "title": "最长上升子序列",
        "description": "给定长度为 n 的整数序列，请输出最长严格上升子序列的长度。子序列不要求连续。",
        "input": "第一行输入 n。第二行输入 n 个整数。",
        "output": "输出一个整数，表示最长严格上升子序列长度。",
        "constraints": "1 <= n <= 5000。",
        "tests": [
            {"input": "5\n1 3 2 4 5\n", "output": "4\n"},
            {"input": "5\n5 4 3 2 1\n", "output": "1\n"},
            {"input": "6\n2 2 2 2 2 2\n", "output": "1\n"},
            {"input": "8\n10 9 2 5 3 7 101 18\n", "output": "4\n"},
            {"input": "7\n1 2 3 4 5 6 7\n", "output": "7\n"},
        ],
    },
    {
        "id": "p-official-big-add",
        "category": "高精度入门",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "title": "高精度加法",
        "description": "给定两个非负整数 a 和 b，它们可能很长。请输出 a+b。",
        "input": "输入两行，分别为 a 和 b。",
        "output": "输出一个整数，表示 a+b。",
        "constraints": "0 <= a,b；数字长度不超过 10000。",
        "tests": [
            {"input": "123\n456\n", "output": "579\n"},
            {"input": "999\n1\n", "output": "1000\n"},
            {"input": "0\n0\n", "output": "0\n"},
            {"input": "1000000000000000000\n1\n", "output": "1000000000000000001\n"},
            {"input": "987654321987654321\n123456789123456789\n", "output": "1111111111111111110\n"},
        ],
    },
    {
        "id": "p-official-top-k",
        "category": "堆",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "title": "第 K 大数",
        "description": "给定 n 个整数和 k，请输出第 k 大的数。若有相同数，按出现次数分别计入排名。",
        "input": "第一行输入 n 和 k。第二行输入 n 个整数。",
        "output": "输出一个整数，表示第 k 大的数。",
        "constraints": "1 <= k <= n <= 100000。",
        "tests": [
            {"input": "5 2\n3 1 5 2 4\n", "output": "4\n"},
            {"input": "4 3\n7 7 6 5\n", "output": "6\n"},
            {"input": "1 1\n42\n", "output": "42\n"},
            {"input": "6 4\n9 1 9 2 8 3\n", "output": "3\n"},
            {"input": "5 5\n5 4 3 2 1\n", "output": "1\n"},
        ],
    },
    {
        "id": "p-official-quick-power",
        "category": "数论",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "title": "快速幂取模",
        "description": "给定 a、b、m，请输出 a 的 b 次方对 m 取模的结果。",
        "input": "输入一行，包含三个整数 a、b、m。",
        "output": "输出一个整数。",
        "constraints": "0 <= a,b <= 10^18；1 <= m <= 10^9。",
        "tests": [
            {"input": "2 10 1000\n", "output": "24\n"},
            {"input": "3 0 7\n", "output": "1\n"},
            {"input": "5 3 13\n", "output": "8\n"},
            {"input": "10 9 6\n", "output": "4\n"},
            {"input": "123456789 2 1000\n", "output": "521\n"},
        ],
    },
    {
        "id": "p-official-rotate-array",
        "category": "数组",
        "difficulty": 4,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "title": "数组循环右移",
        "description": "给定长度为 n 的数组和整数 k，请将数组循环右移 k 位后输出。",
        "input": "第一行输入 n 和 k。第二行输入 n 个整数。",
        "output": "输出右移后的数组。",
        "constraints": "1 <= n <= 100000；0 <= k <= 10^9。",
        "tests": [
            {"input": "5 2\n1 2 3 4 5\n", "output": "4 5 1 2 3\n"},
            {"input": "4 0\n7 8 9 10\n", "output": "7 8 9 10\n"},
            {"input": "3 4\n1 2 3\n", "output": "3 1 2\n"},
            {"input": "1 100\n5\n", "output": "5\n"},
            {"input": "6 3\n1 1 2 2 3 3\n", "output": "2 3 3 1 1 2\n"},
        ],
    },
    {
        "id": "p-official-matrix-border",
        "category": "二维数组",
        "difficulty": 4,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "title": "矩阵边界和",
        "description": "给定 n 行 m 列矩阵，请输出边界元素之和。若只有一行或一列，元素只计算一次。",
        "input": "第一行输入 n 和 m。接下来 n 行，每行 m 个整数。",
        "output": "输出一个整数，表示边界和。",
        "constraints": "1 <= n,m <= 1000。",
        "tests": [
            {"input": "3 3\n1 2 3\n4 5 6\n7 8 9\n", "output": "40\n"},
            {"input": "1 4\n1 2 3 4\n", "output": "10\n"},
            {"input": "4 1\n1\n2\n3\n4\n", "output": "10\n"},
            {"input": "2 2\n5 6\n7 8\n", "output": "26\n"},
            {"input": "3 4\n1 1 1 1\n2 9 9 2\n3 3 3 3\n", "output": "20\n"},
        ],
    },
    {
        "id": "p-official-date-next",
        "category": "模拟",
        "difficulty": 4,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "title": "下一天日期",
        "description": "给定一个合法日期 y m d，请输出下一天的日期。",
        "input": "输入一行，包含三个整数 y、m、d。",
        "output": "输出三个整数，表示下一天的年、月、日。",
        "constraints": "1900 <= y <= 2100。",
        "tests": [
            {"input": "2026 3 15\n", "output": "2026 3 16\n"},
            {"input": "2024 2 28\n", "output": "2024 2 29\n"},
            {"input": "2025 2 28\n", "output": "2025 3 1\n"},
            {"input": "2025 12 31\n", "output": "2026 1 1\n"},
            {"input": "2000 2 29\n", "output": "2000 3 1\n"},
        ],
    },
    {
        "id": "p-official-topological",
        "category": "图论入门",
        "difficulty": 5,
        "source": "CCF GESP 2025-2026 C++ 四级/五级公开真题考点改编",
        "title": "是否存在入度为零的点",
        "description": "给定一个有向图，请统计入度为 0 的点的数量。",
        "input": "第一行输入 n 和 m。接下来 m 行，每行输入一条有向边 u v。",
        "output": "输出一个整数，表示入度为 0 的点数。",
        "constraints": "1 <= n <= 100000；0 <= m <= 200000。",
        "tests": [
            {"input": "4 3\n1 2\n1 3\n3 4\n", "output": "1\n"},
            {"input": "3 0\n", "output": "3\n"},
            {"input": "3 3\n1 2\n2 3\n3 1\n", "output": "0\n"},
            {"input": "5 2\n2 3\n4 3\n", "output": "4\n"},
            {"input": "1 0\n", "output": "1\n"},
        ],
    },
]


CHOICE_QUESTIONS.extend(OFFICIAL_STYLE_CHOICE_QUESTIONS_EXTRA)
PROGRAMMING_TASKS.extend(OFFICIAL_STYLE_PROGRAMMING_TASKS_EXTRA)
