CHOICE_QUESTIONS = [
    {
        "id": "c-arith-001",
        "category": "表达式",
        "difficulty": 3,
        "stem": "下面程序片段的输出结果是？",
        "code": "int a = 19, b = 4;\ncout << a / b + a % b * 2;",
        "options": ["7", "10", "11", "19"],
        "answer": 1,
    },
    {
        "id": "c-loop-001",
        "category": "嵌套循环",
        "difficulty": 4,
        "stem": "下面程序片段的输出结果是？",
        "code": "int cnt = 0;\nfor (int i = 1; i <= 5; i++) {\n    for (int j = 1; j <= i; j++) {\n        if ((i + j) % 2 == 0) {\n            cnt++;\n        }\n    }\n}\ncout << cnt;",
        "options": ["6", "8", "9", "15"],
        "answer": 2,
    },
    {
        "id": "c-string-001",
        "category": "字符串",
        "difficulty": 4,
        "stem": "下面程序片段的输出结果是？",
        "code": "string s = \"p10q25\";\nint x = 0;\nfor (int i = 0; i < s.size(); i++) {\n    if (s[i] >= '0' && s[i] <= '9') {\n        x = x * 10 + (s[i] - '0');\n    }\n}\ncout << x;",
        "options": ["35", "1025", "125", "10025"],
        "answer": 1,
    },
    {
        "id": "c-prime-001",
        "category": "筛法质数",
        "difficulty": 4,
        "stem": "用筛法标记 2 到 70 的合数，最后未被标记的数有多少个？",
        "code": "",
        "options": ["18", "19", "20", "21"],
        "answer": 1,
    },
    {
        "id": "c-sort-001",
        "category": "排序",
        "difficulty": 4,
        "stem": "执行下面一趟冒泡排序后，数组 a 的内容是？",
        "code": "int a[6] = {6, 1, 5, 2, 4, 3};\nfor (int j = 0; j < 5; j++) {\n    if (a[j] > a[j + 1]) {\n        int t = a[j];\n        a[j] = a[j + 1];\n        a[j + 1] = t;\n    }\n}",
        "options": ["{1, 5, 2, 4, 3, 6}", "{1, 2, 3, 4, 5, 6}", "{1, 6, 2, 4, 3, 5}", "{6, 5, 4, 3, 2, 1}"],
        "answer": 0,
    },
    {
        "id": "c-array2-001",
        "category": "二维数组",
        "difficulty": 4,
        "stem": "下面程序片段的输出结果是？",
        "code": "int a[3][3] = {\n    {5, 1, 2},\n    {4, 7, 3},\n    {6, 8, 9}\n};\nint s = 0;\nfor (int i = 0; i < 3; i++) {\n    s += a[i][2 - i];\n}\ncout << s;",
        "options": ["12", "15", "18", "21"],
        "answer": 1,
    },
    {
        "id": "c-rec-001",
        "category": "递归递推",
        "difficulty": 4,
        "stem": "下面函数调用 f(6) 的返回值是？",
        "code": "int f(int n) {\n    if (n <= 2) {\n        return 1;\n    }\n    return f(n - 1) + f(n - 2);\n}",
        "options": ["5", "8", "13", "21"],
        "answer": 1,
    },
    {
        "id": "c-binary-001",
        "category": "二分查找",
        "difficulty": 4,
        "stem": "下面二分查找程序的输出结果是？",
        "code": "int a[7] = {2, 4, 6, 8, 10, 12, 14};\nint l = 0, r = 6, x = 10, ans = -1;\nwhile (l <= r) {\n    int mid = (l + r) / 2;\n    if (a[mid] == x) {\n        ans = mid;\n        break;\n    } else if (a[mid] < x) {\n        l = mid + 1;\n    } else {\n        r = mid - 1;\n    }\n}\ncout << ans;",
        "options": ["3", "4", "5", "-1"],
        "answer": 1,
    },
    {
        "id": "c-logic-001",
        "category": "逻辑表达式",
        "difficulty": 3,
        "stem": "下面程序片段的输出结果是？",
        "code": "int x = 18;\ncout << (x % 2 == 0 && x % 5 == 0 || x % 3 == 0);",
        "options": ["0", "1", "2", "3"],
        "answer": 1,
    },
    {
        "id": "c-enum-001",
        "category": "枚举计数",
        "difficulty": 3,
        "stem": "从数字 1、2、3、4、5 中选出两个不同数字组成两位数，其中偶数有多少个？",
        "code": "",
        "options": ["6", "8", "10", "20"],
        "answer": 1,
    },
    {
        "id": "c-array-001",
        "category": "数组",
        "difficulty": 3,
        "stem": "下面程序片段的输出结果是？",
        "code": "int a[5] = {2, 4, 6, 8, 10};\ncout << a[1] + a[3];",
        "options": ["6", "10", "12", "14"],
        "answer": 2,
    },
    {
        "id": "c-array-002",
        "category": "数组",
        "difficulty": 3,
        "stem": "下面程序片段的输出结果是？",
        "code": "int a[6] = {3, 1, 4, 1, 5, 9};\nint mx = a[0];\nfor (int i = 1; i < 6; i++) {\n    if (a[i] > mx) {\n        mx = a[i];\n    }\n}\ncout << mx;",
        "options": ["1", "4", "5", "9"],
        "answer": 3,
    },
    {
        "id": "c-loop-002",
        "category": "循环",
        "difficulty": 3,
        "stem": "下面程序片段的输出结果是？",
        "code": "int sum = 0;\nfor (int i = 1; i <= 5; i++) {\n    sum += i;\n}\ncout << sum;",
        "options": ["5", "10", "15", "20"],
        "answer": 2,
    },
    {
        "id": "c-sort-002",
        "category": "排序",
        "difficulty": 4,
        "stem": "下面选择排序执行完 i == 0 这一轮后，数组 a 为？",
        "code": "int a[5] = {6, 4, 2, 5, 3};\nint k = 0;\nfor (int j = 1; j < 5; j++) {\n    if (a[j] < a[k]) {\n        k = j;\n    }\n}\nint t = a[0];\na[0] = a[k];\na[k] = t;",
        "options": ["{2, 4, 6, 5, 3}", "{3, 4, 2, 5, 6}", "{6, 4, 2, 5, 3}", "{2, 3, 4, 5, 6}"],
        "answer": 0,
    },
    {
        "id": "c-short-001",
        "category": "逻辑表达式",
        "difficulty": 4,
        "stem": "下面程序片段的输出结果是？",
        "code": "int x = 10;\ncout << (x > 5 || x / 0 == 1);",
        "options": ["0", "1", "运行时错误", "编译错误"],
        "answer": 1,
    },
    {
        "id": "c-div-001",
        "category": "整除统计",
        "difficulty": 3,
        "stem": "1 到 90 中能被 2、3、5 中至少一个整除的整数有多少个？",
        "code": "",
        "options": ["60", "66", "68", "72"],
        "answer": 1,
    },
    {
        "id": "c-factor-001",
        "category": "整除统计",
        "difficulty": 3,
        "stem": "下面程序片段的输出结果是？",
        "code": "int x = 24;\nint cnt = 0;\nfor (int i = 1; i * i <= x; i++) {\n    if (x % i == 0) {\n        cnt++;\n        if (i * i != x) {\n            cnt++;\n        }\n    }\n}\ncout << cnt;",
        "options": ["6", "8", "10", "12"],
        "answer": 1,
    },
]


PROGRAMMING_TASKS = [
    {
        "id": "p-row-col",
        "category": "二维数组",
        "difficulty": 4,
        "title": "矩阵十字和",
        "description": "给定一个 n 行 m 列的整数矩阵，以及一个位置 (x, y)。请输出第 x 行与第 y 列所有元素之和，交叉位置只计算一次。行列编号从 1 开始。",
        "input": "第一行输入 n 和 m。接下来 n 行，每行 m 个整数。最后一行输入 x 和 y。",
        "output": "输出一个整数，表示矩阵十字和。",
        "constraints": "1 <= n, m <= 50；矩阵元素为 0 到 1000 的整数。",
        "tests": [
            {"input": "3 3\n1 2 3\n4 5 6\n7 8 9\n2 2\n", "output": "25\n"},
            {"input": "2 4\n1 1 1 1\n2 2 2 2\n1 3\n", "output": "6\n"},
            {"input": "4 2\n3 5\n7 9\n1 4\n6 8\n4 1\n", "output": "25\n"},
            {"input": "1 5\n2 4 6 8 10\n1 4\n", "output": "30\n"},
            {"input": "2 2\n10 20\n30 40\n2 2\n", "output": "90\n"},
        ],
    },
    {
        "id": "p-prime-count",
        "category": "筛法质数",
        "difficulty": 4,
        "title": "区间质数个数",
        "description": "给定两个整数 L 和 R，请统计闭区间 [L, R] 中质数的个数。",
        "input": "输入一行，包含两个整数 L 和 R。",
        "output": "输出一个整数，表示区间内质数的个数。",
        "constraints": "1 <= L <= R <= 100000。",
        "tests": [
            {"input": "1 10\n", "output": "4\n"},
            {"input": "14 20\n", "output": "2\n"},
            {"input": "30 50\n", "output": "5\n"},
            {"input": "90 100\n", "output": "1\n"},
            {"input": "997 1009\n", "output": "3\n"},
        ],
    },
    {
        "id": "p-tasks",
        "category": "贪心",
        "difficulty": 4,
        "title": "最多完成任务数",
        "description": "有 n 个任务，每个任务需要一定时间。小杨总时间为 T，每个任务最多完成一次。为了完成尽量多的任务，请输出最多能完成几个任务。",
        "input": "第一行输入 n 和 T。第二行输入 n 个正整数，表示每个任务需要的时间。",
        "output": "输出一个整数，表示最多能完成的任务数量。",
        "constraints": "1 <= n <= 1000；1 <= T <= 100000；每个任务耗时为 1 到 100000。",
        "tests": [
            {"input": "5 10\n1 3 4 6 8\n", "output": "3\n"},
            {"input": "6 12\n5 1 2 7 3 4\n", "output": "4\n"},
            {"input": "5 7\n8 9 10 11 12\n", "output": "0\n"},
            {"input": "7 15\n1 1 2 2 3 8 9\n", "output": "5\n"},
            {"input": "8 9\n4 4 4 1 1 1 10 2\n", "output": "5\n"},
        ],
    },
    {
        "id": "p-longest-rise",
        "category": "数组",
        "difficulty": 4,
        "title": "最长连续上升段",
        "description": "给定一个长度为 n 的整数序列，请求出最长连续上升段的长度。连续上升段要求相邻后一个数严格大于前一个数。",
        "input": "第一行输入 n。第二行输入 n 个整数。",
        "output": "输出一个整数，表示最长连续上升段的长度。",
        "constraints": "1 <= n <= 100000；序列元素为 int 范围内整数。",
        "tests": [
            {"input": "5\n1 2 3 2 5\n", "output": "3\n"},
            {"input": "6\n6 5 4 3 2 1\n", "output": "1\n"},
            {"input": "7\n1 3 5 7 9 11 13\n", "output": "7\n"},
            {"input": "8\n2 2 3 4 1 2 3 0\n", "output": "3\n"},
            {"input": "10\n1 2 1 2 3 4 0 1 2 3\n", "output": "4\n"},
        ],
    },
    {
        "id": "p-recurrence",
        "category": "递推",
        "difficulty": 4,
        "title": "递推数列",
        "description": "定义数列 f(1)=1，f(2)=2。当 n>=3 时，f(n)=f(n-1)+2*f(n-2)。给定 n，请输出 f(n)。",
        "input": "输入一个整数 n。",
        "output": "输出 f(n) 的值。",
        "constraints": "1 <= n <= 40，答案在 long long 范围内。",
        "tests": [
            {"input": "1\n", "output": "1\n"},
            {"input": "2\n", "output": "2\n"},
            {"input": "5\n", "output": "16\n"},
            {"input": "10\n", "output": "512\n"},
            {"input": "30\n", "output": "536870912\n"},
        ],
    },
]
